### PR TITLE
Add surrounding whitespace to inlineMatchers

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/ngs/draft-js-markdown-shortcuts-plugin/issues/39

### CODE REVIEW

**Comment by sugarshin** [comment]
Thank you for this contribution.
Can you please rebase from master branch? And I think maybe test is failed, also please fix that.

**Comment by cmslewis** [comment]
@gnestor @sugarshin Big +1 for this. Can I help get the PR across the finish line? Would it take the load off if I just open a new PR?

**Comment by gnestor** [comment]
@cmslewis Yes, please do! I'm just having trouble with the tests. Feel free to implement this better 👍 I saw another PR that is similar and also appears stalled: https://github.com/ngs/draft-js-markdown-shortcuts-plugin/pull/16

**Comment by gnestor** [comment]
@cmslewis I actually made quite a bit of progress on this today 😃 Tests are passing without _hardly_ any tweaking 👍 Let's hope the tasks above pass. Would appreciate your review 👍

**Comment by gnestor** [comment]
@sugarshin It looks like tests are passing but it looks like coveralls config is missing?

**Comment by sugarshin** [comment]
@gnestor Thank you for your work! I'll check later.

**Comment by gnestor** [comment]
Ping @sugarshin 🛎

**Comment by sugarshin** [comment]
@gnestor LGTM! Sorry late reply.

**Comment by gnestor** [comment]
@sugarshin How can we fix this coveralls situation?

**Comment by sugarshin** [comment]
@gnestor Sorry for late reply... I published new version to npm. https://www.npmjs.com/package/draft-js-markdown-shortcuts-plugin

**Pull request merged**
